/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import javax.swing.JOptionPane;
import obligatorio2ingsoftware.Sistema;
import obligatorio2ingsoftware.Articulo;
import javax.swing.ListSelectionModel;
import javax.swing.JList;

/**
 *
 * @author Usuario
 */
public class VentanaEditarArticulos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEditarArticulos
     */
    public VentanaEditarArticulos(Sistema unSistema) {
        initComponents();
        modelo=unSistema;
        this.setLocationRelativeTo(null);
        lstArticulos.setListData(modelo.getListaArticulos().toArray());
        lstArticulos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstArticulos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonBorarArticulo = new javax.swing.JButton();
        jButtonAgregarArticulo = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAtras1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 560));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 560));
        jPanel1.setLayout(null);

        lstArticulos.setBackground(new java.awt.Color(204, 255, 204));
        lstArticulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-Item 1", "-Item 2", "-Item 3", "-Item 4", "-Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstArticulos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 150, 260, 350);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista Articulos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 120, 140, 22);

        jButtonBorarArticulo.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBorarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jButtonBorarArticulo.setBorder(null);
        jButtonBorarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorarArticulo);
        jButtonBorarArticulo.setBounds(410, 460, 70, 40);

        jButtonAgregarArticulo.setBackground(new java.awt.Color(51, 204, 0));
        jButtonAgregarArticulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregarArticulo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarArticulo.setText("Agregar Articulo");
        jButtonAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarArticulo);
        jButtonAgregarArticulo.setBounds(460, 160, 180, 25);

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButtonAtras.setBorder(null);
        jButtonAtras.setMaximumSize(new java.awt.Dimension(63, 63));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(63, 63));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras);
        jButtonAtras.setBounds(20, 490, 70, 60);

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 100));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edición de Articulos");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1680, 80);

        jButtonAtras1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home (1).png"))); // NOI18N
        jButtonAtras1.setBorder(null);
        jButtonAtras1.setMaximumSize(new java.awt.Dimension(63, 63));
        jButtonAtras1.setMinimumSize(new java.awt.Dimension(63, 63));
        jButtonAtras1.setPreferredSize(new java.awt.Dimension(63, 63));
        jButtonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtras1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtras1);
        jButtonAtras1.setBounds(722, 500, 60, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorarArticuloActionPerformed
        // TODO add your handling code here:
        Articulo art= (Articulo)lstArticulos.getSelectedValue();
        if(art!=null){
            modelo.eliminarArticulo(art);
        lstArticulos.setListData(modelo.getListaArticulos().toArray());
        }
        else{
            JOptionPane.showMessageDialog(this,"Seleccione un articulo de la lista", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonBorarArticuloActionPerformed

    private void jButtonAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarArticuloActionPerformed
        // TODO add your handling code here:
        VentanaAgregarArticulo vent=new VentanaAgregarArticulo(modelo);
        vent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgregarArticuloActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        VentanaVendedor vent = new VentanaVendedor(modelo);
        this.setVisible(false);
        vent.setVisible(true);
        vent.setResizable(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtras1ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal vent = new VentanaPrincipal(modelo);
        this.setVisible(false);
        vent.setVisible(true);
        vent.setResizable(false);
    }//GEN-LAST:event_jButtonAtras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarArticulo;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonAtras1;
    private javax.swing.JButton jButtonBorarArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstArticulos;
    // End of variables declaration//GEN-END:variables

    private Sistema modelo;
}
