/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import java.util.*;
import javax.swing.JOptionPane;
import obligatorio2ingsoftware.Sistema;
import obligatorio2ingsoftware.Articulo;
import obligatorio2ingsoftware.Venta;
import obligatorio2ingsoftware.Cliente;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author tomasmartinez
 */
public class VentanaCompra1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCompra
     */
    public VentanaCompra1(Sistema unSistema) {
        initComponents();
        modelo = unSistema;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCafe1 = new javax.swing.JComboBox<>();
        jLabelKombucha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPasas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCafe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelHongos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxPasas = new javax.swing.JComboBox();
        jComboBoxCafe = new javax.swing.JComboBox<>();
        jComboBoxHongos = new javax.swing.JComboBox<>();
        jComboBoxKombucha = new javax.swing.JComboBox<>();
        jButtonComprar = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jComboBoxCafe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 560));
        setMinimumSize(new java.awt.Dimension(800, 560));
        setPreferredSize(new java.awt.Dimension(800, 560));

        jLabelKombucha.setText("IMAGEN KOMBUCHA");
        jLabelKombucha.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelKombucha.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelKombucha.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setText("Pasas de Uva: 200$");

        jLabelPasas.setText("IMAGEN PASAS DE UVA");
        jLabelPasas.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelPasas.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelPasas.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setText("Café Parsero: 500$");

        jLabelCafe.setText("IMAGEN CAFE PARSERO");
        jLabelCafe.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelCafe.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelCafe.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel6.setText("Kombucha: 400$");

        jLabelHongos.setText("IMAGEN HONGOS");
        jLabelHongos.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelHongos.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelHongos.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel8.setText("Hongos Shiitake: 700$");

        jComboBoxPasas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jComboBoxCafe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jComboBoxHongos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jComboBoxKombucha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButtonComprar.setText("COMPRAR");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Cedula de identidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHongos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxPasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHongos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelKombucha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jComboBoxKombucha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonComprar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPasas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxKombucha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelHongos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jComboBoxHongos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKombucha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        // TODO add your handling code here:
        int cantidadPasas = jComboBoxPasas.getSelectedIndex();
        int cantidadCafe = jComboBoxCafe.getSelectedIndex();
        int cantidadHongos = jComboBoxHongos.getSelectedIndex();
        int cantidadKombucha = jComboBoxKombucha.getSelectedIndex();
        
        Venta venta = new Venta();
        
        String ci=txtCedula.getText();
        if(modelo.esNumerico(ci)){
            Cliente aux = new Cliente();
            aux.setCedula(Integer.parseInt(ci));
            if(modelo.estaRegistrado(aux)){
                int pos = modelo.getListaClientes().indexOf(aux);
                
                venta.setCliente(modelo.getListaClientes().get(pos));
                
                Date fecha = new Date();
                venta.setFecha(fecha);
        
                if(cantidadPasas>0){
                    Articulo artPasas = modelo.getListaArticulosOriginales().get(0);
                    artPasas.setCantidadVendidos(cantidadPasas);
                    venta.getListaArticulos().add(artPasas);
                }
                if(cantidadCafe>0){
                    Articulo artCafe = modelo.getListaArticulosOriginales().get(1);
                    artCafe.setCantidadVendidos(cantidadCafe);
                    venta.getListaArticulos().add(artCafe);
                }
                if(cantidadHongos>0){
                    Articulo artHongos = modelo.getListaArticulosOriginales().get(2);
                    artHongos.setCantidadVendidos(cantidadHongos);
                    venta.getListaArticulos().add(artHongos);
                }
                if(cantidadKombucha>0){
                    Articulo artKombucha = modelo.getListaArticulosOriginales().get(3);
                    artKombucha.setCantidadVendidos(cantidadKombucha);
                    venta.getListaArticulos().add(artKombucha);
                }
        
                modelo.getListaVentas().add(venta);
        
                VentanaSeleccionarEnvases vent = new VentanaSeleccionarEnvases(modelo);
                this.setVisible(false);
                vent.setVisible(true);
                vent.setResizable(false);                
            }
            else{
                JOptionPane.showMessageDialog(this, "Cliente No Registrado", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Cedula invalida", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButtonComprarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JComboBox<String> jComboBoxCafe;
    private javax.swing.JComboBox<String> jComboBoxCafe1;
    private javax.swing.JComboBox<String> jComboBoxHongos;
    private javax.swing.JComboBox<String> jComboBoxKombucha;
    private javax.swing.JComboBox jComboBoxPasas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCafe;
    private javax.swing.JLabel jLabelHongos;
    private javax.swing.JLabel jLabelKombucha;
    private javax.swing.JLabel jLabelPasas;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
    Sistema modelo;
}
